#include "../include/songs.h"
#include "../include/display.h"
#include <iostream>

// TODO(fawad): Find a way to display the songs in columns or any other way
void displaySongs(string sortedBy) {
    for (int i = 0; i < songsArray.size(); i++) {
        string songName = songsArray[i].title;
        string artistName = songsArray[i].artist;
        int year = songsArray[i].year;
        int id = songsArray[i].id;
        string genre = songsArray[i].genre;
        string mood = songsArray[i].mood;

        if (sortedBy == "artist") {
            cout << id << "     | " << artistName << "     | " << songName
                 << "    | " << genre << "   | " << year << endl;
        } else if (sortedBy == "song_name") {
            cout << id << "     | " << songName << "     | " << artistName
                 << "    | " << genre << "   | " << year << endl;
        } else if (sortedBy == "genre") {
            cout << id << "     | " << genre << "     | " << songName
                 << "    | " << artistName << "   | " << year << endl;
        } else {
            cout << id << "     | " << year << "     | " << songName << "    | "
                 << artistName << "   | " << genre << endl;
        }
    }
}

int generateId() {
    int id = songsArray.size() + 1;
    cout << songsArray.size();
    return id;
}

void addNewSong() {
    printYellowText("\n>> ADD NEW SONG");
    printYellowText("==================");
    // TODO(fawad): Find a way to deal with song duplication
    string song_name, artist_name, genre;
    int id, year;
    // Song title
    cout << "SONG NAME: ";
    cin.ignore();
    getline(cin, song_name);
    // Artist
    cout << "ARTIST NAME: ";
    getline(cin, artist_name);
    // Genre
    cout << "GENRE: ";
    getline(cin, genre);
    // Year
    cout << "RELEASING YEAR: ";
    cin >> year;
    // ID
    id = generateId();

    Song const song = {id, year, artist_name, song_name, genre, "sad"};
    songsArray.push_back(song);
    printSuccessMessage("Song added successfully");
}

void editSong() {
    printYellowText("\n >> EDIT SONG");
    printYellowText("===============");
    int songID;
    cout << "SONG ID: ";
    cin >> songID;
    // Check if song exists
    for (int i = 0; i < songsArray.size(); i++) {
        int existingSongID = songsArray[i].id;
        if (songID == existingSongID) {
            cout << "SONG FOUND!" << endl;
            string new_title, new_artist, new_genre;
            int new_year;

            cout << "ENTER NEW SONG NAME: ";
            cin.ignore();
            getline(cin, new_title);

            cout << "ENTER NEW ARTIST NAME: ";
            getline(cin, new_artist);

            cout << "ENTER NEW GENRE: ";
            getline(cin, new_genre);

            cout << "ENTER NEW YEAR: ";
            cin >> new_year;

            songsArray[i].title = new_title;
            songsArray[i].artist = new_artist;
            songsArray[i].genre = new_genre;
            songsArray[i].year = new_year;

            printSuccessMessage("Song updated successfully!");
            return;
        }
    }
    printErrorMessage("Song not found");
}

void deleteSong(int songID) {
    // Check if song exists
    for (int i = 0; i < songsArray.size(); i++) {
        int id = songsArray[i].id;
        if (songID == id) {
            songsArray.erase(songsArray.begin() + songID - 1);
            printSuccessMessage("Song deleted successfully");
            return;
        }
    }
    printErrorMessage("Song not found");
}

vector<Song> songsArray = {
    {1, 2022, "Krishnakumar Kunnath",
     "Aankhon mein teri by Krishnakumar Kunnath", "hip-hop", "sad"},
    {2, 2012, "Krishnakumar Kunnath (Ft. Randeep Hooda & Sunny Leone)",
     "Abhi Abhi (Male) by Krishnakumar Kunnath (Ft. Randeep Hooda & Sunny "
     "Leone)",
     "hip-hop", "sad"},
    {3, 2022,
     "Vishal & Shekhar (Ft. Krishnakumar Kunnath, Shreya Ghoshal & Vishal "
     "Dadlani)",
     "Ab To Forever by Vishal & Shekhar (Ft. Krishnakumar Kunnath, Shreya "
     "Ghoshal & Vishal Dadlani)",
     "hip-hop", "sad"},
    {4, 2007, "Krishnakumar Kunnath", "Ajab Si by Krishnakumar Kunnath",
     "hip-hop", "romantic"},
    {5, 2007,
     "Krishnakumar Kunnath (Ft. Krishnakumar Kunnath & Pritam Chakraborty)",
     "Alvida by Krishnakumar Kunnath (Ft. Krishnakumar Kunnath & Pritam "
     "Chakraborty)",
     "hip-hop", "sad"},
    {6, 2020, "Pritam & KK", "Aur Tanha by Pritam & KK", "hip-hop", "sad"},
    {7, 2002,
     "Ismail Darbar (Ft. Kavita Krishnamurthy, Krishnakumar Kunnath & Shreya "
     "Ghoshal)",
     "Dola Re Dola by Ismail Darbar (Ft. Kavita Krishnamurthy, Krishnakumar "
     "Kunnath & Shreya Ghoshal)",
     "hip-hop", "party"},
    {8, 2004,
     "Anu Malik (Ft. Krishnakumar Kunnath, Shreya Ghoshal & Sunidhi Chauhan)",
     "Gori Gori Gori Gori by Anu Malik (Ft. Krishnakumar Kunnath, Shreya "
     "Ghoshal & Sunidhi Chauhan)",
     "hip-hop", "party"},
    {9, 2023, "Pritam (Ft. Krishnakumar Kunnath)",
     "Haan Tu Hai by Pritam (Ft. Krishnakumar Kunnath)", "hip-hop", "sad"},
    {10, 2014,
     "Neeti Mohan (Ft. Krishnakumar Kunnath, Shankar Mahadevan & Vishal "
     "Dadlani)",
     "India Waale by Neeti Mohan (Ft. Krishnakumar Kunnath, Shankar Mahadevan "
     "& Vishal Dadlani)",
     "hip-hop", "party"},
    {11, 2013, "KK & Sonal Chauhan", "Kaise Bataaoon by KK & Sonal Chauhan",
     "hip-hop", "romantic"},
    {12, 2019, "Krishnakumar Kunnath",
     "Kal Ki Hi Baat Hai by Krishnakumar Kunnath", "hip-hop", "sad"},
    {13, 2021, "KK & Sunidhi Chauhan", "Kambakkht Ishq by KK & Sunidhi Chauhan",
     "hip-hop", "party"},
    {14, 2012, "KK & Palak Muchhal", "Laapata by KK & Palak Muchhal", "hip-hop",
     "sad"},
    {15, 2023, "Krishnakumar Kunnath", "Main Kya Hoon by Krishnakumar Kunnath",
     "hip-hop", "party"},
    {16, 2023, "Sohail Sen (Ft. Krishna Beura & Krishnakumar Kunnath)",
     "Mere Brother Ki Dulhan by Sohail Sen (Ft. Krishna Beura & Krishnakumar "
     "Kunnath)",
     "hip-hop", "happy"},
    {17, 2022,
     "A.R. Rahman (Ft. Clinton Cerejo, Krishnakumar Kunnath, Kunal Ganjawala & "
     "Shaan)",
     "O Humdum Suniyo Re by A.R. Rahman (Ft. Clinton Cerejo, Krishnakumar "
     "Kunnath, Kunal Ganjawala & Shaan)",
     "hip-hop", "sad"},
    {18, 2020, "Pritam (Ft. Krishnakumar Kunnath)",
     "O Meri Jaan by Pritam (Ft. Krishnakumar Kunnath)", "hip-hop", "sad"},
    {19, 2021,
     "Pritam (Ft. Krishnakumar Kunnath, Shefali Alvares & Yo Yo Honey Singh)",
     "Party On My Mind by Pritam (Ft. Krishnakumar Kunnath, Shefali Alvares & "
     "Yo Yo Honey Singh)",
     "hip-hop", "party"},
    {20, 2013, "Tulsi Kumar & KK", "Piya Aaye Na by Tulsi Kumar & KK",
     "hip-hop", "sad"},
    {21, 2022, "Krishnakumar Kunnath", "Pyar Ke Pal by Krishnakumar Kunnath",
     "hip-hop", "romantic"},
    {22, 2023, "Jeet Gannguli (Ft. Krishnakumar Kunnath)",
     "Rafta Rafta by Jeet Gannguli (Ft. Krishnakumar Kunnath)", "hip-hop",
     "sad"},
    {23, 2017, "Krishnakumar Kunnath", "Saanson Ke by Krishnakumar Kunnath",
     "hip-hop", "romantic"},
    {24, 2003, "Vishal & Shekhar (Ft. Krishnakumar Kunnath)",
     "Tu Aashiqui Hai by Vishal & Shekhar (Ft. Krishnakumar Kunnath)",
     "hip-hop", "romantic"},
    {25, 2011, "Krishnakumar Kunnath",
     "Tu Aashiqui Hai by Krishnakumar Kunnath", "hip-hop", "romantic"},
    {26, 2011,
     "Sabri Brothers (Ft. Krishnakumar Kunnath, Leslie Lewis, Mathangi & "
     "$anJay)",
     "Tu Hai Yahaan by Sabri Brothers (Ft. Krishnakumar Kunnath, Leslie Lewis, "
     "Mathangi & $anJay)",
     "hip-hop", "sad"},
    {27, 2005, "Krishnakumar Kunnath",
     "Tu Hi Meri Shab Hai by Krishnakumar Kunnath", "hip-hop", "romantic"},
    {28, 2012, "Pritam (Ft. Krishnakumar Kunnath)",
     "Tujhe Sochta Hoon by Pritam (Ft. Krishnakumar Kunnath)", "hip-hop",
     "romantic"},
    {29, 2015, "Pritam & KK", "Tu Jo Mila by Pritam & KK", "hip-hop", "happy"},
    {30, 2021, "Javed Ali (Ft. Krishnakumar Kunnath)",
     "Tu Jo Mila (Dekhna Na Mudke) by Javed Ali (Ft. Krishnakumar Kunnath)",
     "hip-hop", "happy"},
    {31, 2019, "Krishnakumar Kunnath", "Tum Na Aaye by Krishnakumar Kunnath",
     "hip-hop", "sad"},
    {32, 2023, "Krishnakumar Kunnath (Ft. Leslie Lewis)",
     "Yaaron by Krishnakumar Kunnath (Ft. Leslie Lewis)", "hip-hop", "happy"

    },
    {33, 2021, "Shamoon Ismail (Ft. Talha Anjum)",
     "051021 by Shamoon Ismail (Ft. Talha Anjum)", "hip-hop", "party"},
    {34, 2019, "Talha Anjum", "100 Bars by Talha Anjum", "hip-hop", "party"},
    {35, 2020, "Talha Anjum (Ft. Rap Demon & Talhah Yunus)",
     "12 Bajay by Talha Anjum (Ft. Rap Demon & Talhah Yunus)", "hip-hop",
     "party"},
    {36, 2018, "Young Stunners", "32 Bore by Young Stunners", "hip-hop",
     "party"},
    {37, 2022, "Talha Anjum", "4AM in Karachi by Talha Anjum", "hip-hop",
     "party"},
    {38, 2021, "Talha Anjum", "9MM by Talha Anjum", "hip-hop", "party"},
    {39, 2021, "Jokhay (Ft. JANI, Nabeel Akbar & Talha Anjum)",
     "Aarzu by Jokhay (Ft. JANI, Nabeel Akbar & Talha Anjum)", "hip-hop",
     "party"},
    {40, 2020,
     "Zaheer Akhunzada X Shani (Ft. Talha Anjum, Talhah Yunus & Young "
     "Stunners)",
     "Aawara - Shani x Zaheer Akhunzada by Zaheer Akhunzada X Shani (Ft. Talha "
     "Anjum, Talhah Yunus & Young Stunners)",
     "hip-hop", "party"},
    {41, 2022, "Young Stunners (Ft. Bilal Ali, Talha Anjum & Talhah Yunus)",
     "Aazma Le by Young Stunners (Ft. Bilal Ali, Talha Anjum & Talhah Yunus)",
     "hip-hop", "happy"},
    {42, 2020, "Young Stunners", "Afsanay by Young Stunners", "hip-hop", "sad"},
    {43, 2021, "Talha Anjum & Rap Demon", "Agency by Talha Anjum & Rap Demon",
     "hip-hop", "party"},
    {44, 2022, "Cyph   E (Ft. Rap Demon, Talha Anjum & Umair)",
     "Agency(Remix) by Cyph   E (Ft. Rap Demon, Talha Anjum & Umair)",
     "hip-hop", "party"},
    {45, 2019, "Young Stunners", "Asli Hai by Young Stunners", "hip-hop",
     "happy"},
    {46, 2023, "Talha Anjum", "At The Top by Talha Anjum", "hip-hop", "party"},
    {47, 2021, "Talha Anjum, JJ47 & Talhah Yunus (Ft. Young Stunners)",
     "AUQAAT by Talha Anjum, JJ47 & Talhah Yunus (Ft. Young Stunners)",
     "hip-hop", "party"},
    {48, 2021, "Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "Azaad Hain by Young Stunners (Ft. Talha Anjum & Talhah Yunus)", "hip-hop",
     "happy"},
    {49, 2021, "JJ47, Talha Anjum & Talhah Yunus (Ft. Young Stunners)",
     "Baaz by JJ47, Talha Anjum & Talhah Yunus (Ft. Young Stunners)", "hip-hop",
     "party"},
    {50, 2019, "Talha Anjum", "Balli Aur Mein by Talha Anjum", "hip-hop",
     "sad"},

    {51, 2020, "Jokhay", "Bandish by Jokhay", "hip-hop", "party"},
    {52, 2021, "Talha Anjum", "Battle in Style by Talha Anjum", "hip-hop",
     "party"},
    {53, 2023, "KRSNA", "Been a While by KRSNA", "hip-hop", "party"},
    {54, 2022, "Young Stunners", "Benz by Young Stunners", "hip-hop", "party"},
    {55, 2019, "Talhah Yunus", "BHAARI HAIN", "hip-hop", "party"},
    {56, 2020, "High zone records", "BLACK ON BLACK by High zone records",
     "hip-hop", "party"},
    {57, 2013, "Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "Burger e Karachi by Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "hip-hop", "party"},
    {58, 2020, "Young Stunners (Ft. J.Hind)",
     "Cali 2 Karachi by Young Stunners (Ft. J.Hind)", "hip-hop", "party"},
    {59, 2019, "Young Stunners", "Class by Young Stunners", "hip-hop", "party"},
    {60, 2020, "Jokhay", "Darja Haraarat by Jokhay", "hip-hop", "party"},
    {62, 2018, "Young Stunners", "Dear Zainab by Young Stunners", "hip-hop",
     "sad"},
    {63, 2022, "Talha Anjum", "Death Wish by Talha Anjum", "hip-hop", "party"},
    {64, 2023, "Talha Anjum", "Desperation by Talha Anjum", "hip-hop", "party"},
    {65, 2020, "Young Stunners (Ft. Rap Demon)",
     "Dont Mind by Young Stunners (Ft. Rap Demon)", "hip-hop", "party"},
    {66, 2019, "JJ47, Talha Anjum, Talhah Yunus", "Dope Town by JJ47",
     "hip-hop", "party"},
    {67, 2023, "Talha Anjum", "Downers At Dusk by Talha Anjum", "hip-hop",
     "party"},
    {68, 2023, "Young Stunners", "Duur by Young Stunners", "hip-hop", "party"},
    {69, 2020, "Rap Demon (Ft. Talha Anjum)",
     "FALSAFAY by Rap Demon (Ft. Talha Anjum)", "hip-hop", "party"},
    {70, 2023, "Talha Anjum", "False Prophets by Talha Anjum", "hip-hop",
     "party"},
    {71, 2013, "Young Stunners (Ft. Intishaar)",
     "Fikar-E-Akhirat by Young Stunners (Ft. Intishaar)", "hip-hop", "sad"},
    {72, 2023, "Talha Anjum", "Flex by Talha Anjum", "hip-hop", "party"},
    {73, 2019, "Talha Anjum (Ft. Talhah Yunus)",
     "Full Pachaas by Talha Anjum (Ft. Talhah Yunus)", "hip-hop", "party"},
    {74, 2020, "Rap Demon (Ft. Talha Anjum)",
     "Fursat by Rap Demon (Ft. Talha Anjum)", "hip-hop", "party"},
    {75, 2020, "Jokhay (Ft. JANI, JJ47, SAVAGE (PAK), Talha Anjum & Umar)",
     "Gardish by Jokhay (Ft. JANI, JJ47, SAVAGE (PAK), Talha Anjum & Umar)",
     "hip-hop", "party"},
    {76, 2019, "Talha Anjum", "Gawah Rehna by Talha Anjum", "hip-hop", "party"},
    {77, 2020, "Adil Sultan (Ft. Talha Anjum)",
     "Ghaafil by Adil Sultan (Ft. Talha Anjum)", "hip-hop", "party"},
    {78, 2023, "Talha Anjum (Ft. JJ47 & Talhah Yunus)",
     "Glass Half Full by Talha Anjum (Ft. JJ47 & Talhah Yunus)", "hip-hop",
     "party"},
    {79, 2018, "Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "Gucci Gang (Urdu Remix) by Young Stunners (Ft. Talha Anjum & Talhah "
     "Yunus)",
     "hip-hop", "party"},
    {80, 2020, "Young Stunners", "Gumaan by Young Stunners", "hip-hop",
     "party"},
    {81, 2023, "Talha Anjum", "Happy Hour by Talha Anjum", "hip-hop", "party"},
    {82, 2020, "Talha Anjum (Ft. Talhah Yunus & Young Stunners)",
     "Hatto Bacho by Talha Anjum (Ft. Talhah Yunus & Young Stunners)",
     "hip-hop", "party"},
    {83, 2022, "Umair (Ft. Talha Anjum)", "HITLIST by Umair (Ft. Talha Anjum)",
     "hip-hop", "party"},
    {84, 2017, "Young Stunners", "I Don't Know by Young Stunners", "hip-hop",
     "party"},
    {85, 2020, "Young Stunners", "Jalega by Young Stunners", "hip-hop",
     "party"},
    {86, 2019, "Jokhay (Ft. Nabeel Akbar & Talha Anjum)",
     "JAZBAAT by Jokhay (Ft. Nabeel Akbar & Talha Anjum)", "hip-hop", "party"},
    {87, 2019, "Young Stunners", "Jhoolay Laal by Young Stunners", "hip-hop",
     "happy"},
    {88, 2019, "Talha Anjum", "Jokhay Aur Mein by Talha Anjum", "hip-hop",
     "party"},
    {89, 2022, "Young Stunners (Ft. CHEN-K, Talha Anjum & Talhah Yunus)",
     "Jung Wung by Young Stunners (Ft. CHEN-K, Talha Anjum & Talhah Yunus)",
     "hip-hop", "party"},
    {90, 2023, "Talha Anjum", "Kaam Pura by Talha Anjum", "hip-hop", "party"},
    {91, 2020, "Young Stunners (Ft. Yas The Underdog)",
     "Karachi Chal by Young Stunners (Ft. Yas The Underdog)", "hip-hop",
     "party"},
    {92, 2019, "Talha Anjum", "Karachi Mera by Talha Anjum", "hip-hop",
     "happy"},
    {93, 2020, "Jokhay (Ft. JJ47, Nabeel Akbar, Talha Anjum & Talhah Yunus)",
     "Khana Badosh by Jokhay (Ft. JJ47, Nabeel Akbar, Talha Anjum & Talhah "
     "Yunus)",
     "hip-hop", "party"},
    {94, 2020, "Rap Demon (Ft. Talha Anjum & Talhah Yunus)",
     "Khitaab by Rap Demon (Ft. Talha Anjum & Talhah Yunus)", "hip-hop",
     "party"},
    {95, 2021, "Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "Khwabon Ki Jeet by Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "hip-hop", "party"},
    {96, 2022, "Talha Anjum (Ft. Annural Khalid)",
     "Kyun by Talha Anjum (Ft. Annural Khalid)", "hip-hop", "party"},
    {97, 2021, "Young Stunners", "Laga Reh by Young Stunners", "hip-hop",
     "happy"},
    {98, 2023, "Talha Anjum", "Lost In Time by Talha Anjum", "hip-hop",
     "party"},
    {99, 2023, "Talha Anjum", "Lost Time by Talha Anjum", "hip-hop", "party"},
    {100, 2021, "Somee chohan & Talha Anjum",
     "Marjaaneya by Somee chohan & Talha Anjum", "hip-hop", "sad"},
    {101, 2019, "Talha Anjum", "Mein Aur Mere Idols by Talha Anjum", "hip-hop",
     "party"},
    {102, 2023, "Talha Anjum", "Melancholy by Talha Anjum", "hip-hop", "sad"},
    {103, 2018, "Talha Anjum", "Muntazir by Talha Anjum", "hip-hop", "sad"},
    {104, 2022, "Young Stunners", "Naya Pakistan by Young Stunners", "hip-hop",
     "party"},
    {105, 2022, "Umair (Ft. Calm & Talha Anjum)",
     "Nevermind by Umair (Ft. Calm & Talha Anjum)", "hip-hop", "party"},
    {106, 2019, "Young Stunners", "Next Level by Young Stunners", "hip-hop",
     "party"},
    {107, 2017, "Young Stunners", "No Hook Ups by Young Stunners", "hip-hop",
     "party"},
    {108, 2022, "Umair (Ft. Talha Anjum)",
     "No other Place by Umair (Ft. Talha Anjum)", "hip-hop", "party"},
    {109, 2023, "JJ47 (Ft. Talha Anjum & Talhah Yunus)",
     "ON ME by JJ47 (Ft. Talha Anjum & Talhah Yunus)", "hip-hop", "party"},
    {110, 2023, "Talha Anjum", "Open Letter by Talha Anjum", "hip-hop",
     "party"},
    {111, 2022, "Talha Anjum (Ft. Talha Anjum & Yas The Underdog)",
     "Overseas Connect by Talha Anjum (Ft. Talha Anjum & Yas The Underdog)",
     "hip-hop", "party"},
    {112, 2022, "Talha Anjum (Ft. Umair)",
     "Pain Killers by Talha Anjum (Ft. Umair)", "hip-hop", "party"},
    {113, 2022, "Umer Anjum", "Pest Control by Umer Anjum", "hip-hop", "party"},
    {114, 2022, "Faisal Kapadia (Ft. Young Stunners)",
     "Phir Milenge by Faisal Kapadia (Ft. Young Stunners)", "hip-hop", "party"},
    {115, 2018, "Young Stunners", "Po Po by Young Stunners", "hip-hop",
     "party"},
    {116, 2020, "SAVAGE & Talha Anjum", "POWER TRIP by SAVAGE & Talha Anjum",
     "hip-hop", "party"},
    {117, 2019, "Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "Pretty Little Fears (Urdu Remix) by Young Stunners (Ft. Talha Anjum & "
     "Talhah Yunus)",
     "hip-hop", "party"},
    {118, 2019, "Young Stunners (Ft. JJ47, Talha Anjum & Talhah Yunus)",
     "PSYCHO by Young Stunners (Ft. JJ47, Talha Anjum & Talhah Yunus)",
     "hip-hop", "party"},
    {119, 2020, "Young Stunners (Ft. KR$NA, Talha Anjum & Talhah Yunus)",
     "Quarantine by Young Stunners (Ft. KR$NA, Talha Anjum & Talhah Yunus)",
     "hip-hop", "party"},
    {120, 2021, "Jokhay (Ft. Hashim Nawaz & Talha Anjum)",
     "Raabta by Jokhay (Ft. Hashim Nawaz & Talha Anjum)", "hip-hop", "party"},
    {121, 2017, "Young Stunners", "Real Talk by Young Stunners", "hip-hop",
     "party"},
    {122, 2017, "Young Stunners", "Right Now by Young Stunners", "hip-hop",
     "party"},
    {123, 2020, "Young Stunners", "Rooh (Remix) by Young Stunners", "hip-hop",
     "sad"},
    {124, 2022, "Jokhay (Ft. JJ47, Shareh & Talha Anjum)",
     "Sabar by Jokhay (Ft. JJ47, Shareh & Talha Anjum)", "hip-hop", "party"},
    {125, 2023, "Talha Anjum", "Secrets by Talha Anjum", "hip-hop", "party"},
    {126, 2019, "Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "Shaking My Head #SMH by Young Stunners (Ft. Talha Anjum & Talhah Yunus)",
     "hip-hop", "party"},
    {127, 2020, "Rap Demon (Ft. Somee chohan & Talha Anjum)",
     "SHOWSTOPPER by Rap Demon (Ft. Somee chohan & Talha Anjum)", "hip-hop",
     "party"},
    {128, 2023, "Talha Anjum (Ft. Rap Demon)",
     "Studio Gangsters by Talha Anjum (Ft. Rap Demon)", "hip-hop", "party"},
    {129, 2021, "Young Stunners (Ft. Aima Baig, Talha Anjum & Talhah Yunus)",
     "Stunner by Young Stunners (Ft. Aima Baig, Talha Anjum & Talhah Yunus)",
     "hip-hop", "party"},
    {130, 2020, "Rap Demon (Ft. Talha Anjum, Talhah Yunus & Young Stunners)",
     "Stunner Flow by Rap Demon (Ft. Talha Anjum, Talhah Yunus & Young "
     "Stunners)",
     "hip-hop", "party"},
    {131, 2021, "Abdullah Siddiqui & Talha Anjum",
     "Surface by Abdullah Siddiqui & Talha Anjum", "hip-hop", "sad"},
    {132, 2023, "Young Stunners", "Talk To Me by Young Stunners", "hip-hop"},
    {133, 2021, "Dua Lipa", "21 Grams by Dua Lipa", "pop", "party"},
    {134, 2020, "Dua Lipa", "25/8 by Dua Lipa", "pop", "party"},
    {135, 2021, "Dua Lipa", "Act of God by Dua Lipa (Ft. Ant Clemons)", "pop",
     "party"},
    {136, 2021, "Dua Lipa", "Act of God (Demo) by Dua Lipa (Ft. Ant Clemons)",
     "pop", "party"},
    {137, 2021, "Dua Lipa", "A Different Way by Dua Lipa", "pop", "party"},
    {138, 2023, "Dua Lipa", "AfterIight by Dua Lipa", "pop", "party"},
    {139, 2022, "Dua Lipa", "Afterlight (Demo) by Dua Lipa", "pop", "party"},
    {140, 2014, "Dua Lipa", "All of Me by Dua Lipa", "pop", "party"},
    {141, 2023, "Dua Lipa", "All or Nothing by Dua Lipa", "pop", "party"},
    {142, 2021, "Dua Lipa", "All The Money In The World by Dua Lipa", "pop",
     "party"},
    {143, 2022, "Dua Lipa", "All to Myself by Dua Lipa", "pop", "party"},
    {144, 2023, "Dua Lipa", "Already Gone by Dua Lipa", "pop", "party"},
    {145, 2022, "Post Malone",
     "Apart by Post Malone (Ft. DaBaby, Dua Lipa & Roddy Ricch)", "pop",
     "party"},
    {146, 2021, "Genius", "Artist Archive: Dua Lipa by Genius (Ft. Dua Lipa)",
     "pop", "party"},
    {147, 2021, "Dua Lipa", "Babylon (Demo 1) by Dua Lipa", "pop", "party"},
    {148, 2023, "Dua Lipa", "Babylon (Demo 2/Rework 1) by Dua Lipa", "pop",
     "party"},
    {149, 2022, "Dua Lipa", "Babylon (Rework 2) by Dua Lipa", "pop", "party"},
    {150, 2021, "Dua Lipa", "Bad Idea by Dua Lipa", "pop", "party"},
    {151, 2022, "Dua Lipa", "Bad Self by Dua Lipa", "pop", "party"},
    {152, 2017, "Dua Lipa", "Bad Together by Dua Lipa", "pop", "party"},
    {153, 2017, "Dua Lipa", "Bad Together (Demo) by Dua Lipa", "pop", "party"},
    {154, 2019, "Ariana Grande, Normani & Nicki Minaj",
     "Bad to You by Ariana Grande, Normani & Nicki Minaj", "pop", "party"},
    {155, 2023, "Ariana Grande & Dua Lipa",
     "Bad to You (Demo 1) by Ariana Grande & Dua Lipa (Ft. Dua Lipa)", "pop",
     "party"},
    {156, 2021, "Ariana Grande & Dua Lipa",
     "Bad to You (Demo 2) by Ariana Grande & Dua Lipa", "pop", "party"},
    {157, 2020, "Dua Lipa", "Ball & Chain by Dua Lipa", "pop", "party"},
    {158, 2020, "Dua Lipa", "Ball & Chain (Demo) by Dua Lipa", "pop", "party"},
    {159, 2017, "Dua Lipa", "Bang Bang by Dua Lipa", "pop", "party"},
    {160, 2020, "Dua Lipa", "Bang Bang (Commercial Version) by Dua Lipa", "pop",
     "party"},
    {161, 2021, "Dua Lipa", "Beautiful Nothing by Dua Lipa", "pop", "party"},
    {162, 2015, "Dua Lipa", "Beg by Dua Lipa", "pop", "party"},
    {163, 2021, "Dua Lipa", "Beg (Demo) by Dua Lipa", "pop", "party"},
    {164, 2021, "Dua Lipa", "Beg for It by Dua Lipa", "pop", "party"},
    {165, 2021, "Dua Lipa", "Beg for It (Demo) by Dua Lipa", "pop", "party"},
    {166, 2017, "Dua Lipa", "Begging by Dua Lipa", "pop", "party"},
    {167, 2022, "Dua Lipa", "Begging (Demo) by Dua Lipa (Ft. Cara Salimando)",
     "pop", "party"},
    {168, 2020, "TWICE", "BEHIND THE MASK by TWICE", "pop", "party"},
    {169, 2020, "Dua Lipa", "Berlin Summer by Dua Lipa", "pop", "party"},
    {170, 2019, "2019 Grammy Awards",
     "Best New Artist Nominees by 2019 Grammy Awards", "pop", "party"},
    {171, 2015, "Dua Lipa", "Be the One by Dua Lipa", "pop", "party"},
    {172, 2020, "Dua Lipa", "Be The One (Demo) by Dua Lipa", "pop", "party"},
    {173, 2016, "Dua Lipa", "Be the One (Dillistone Remix) by Dua Lipa", "pop",
     "party"},
    {174, 2015, "Dua Lipa", "Be the One (Netsky Remix) by Dua Lipa", "pop",
     "party"},
    {175, 2016, "Dua Lipa", "Be the One (Roman Tkachoff Remix) by Dua Lipa",
     "pop", "party"},
    {176, 2021, "Dua Lipa",
     "Be The One (Rough Demo) by Dua Lipa (Ft. Bronwyn Ellis)", "pop", "party"},
    {177, 2015, "Dua Lipa",
     "Be the One (Shy Luv Remix) by Dua Lipa (Ft. Aminé)", "pop", "party"},
    {178, 2022, "Dua Lipa",
     "Be The One (Vaggelis Pap & P. Zaphiropoulos Remix) by Dua Lipa", "pop",
     "party"},
    {179, 2020, "Dua Lipa", "Better This Way by Dua Lipa", "pop", "party"},
    {180, 2020, "Dua Lipa", "Between a Bullet and a Heartbreak by Dua Lipa",
     "pop", "party"},
    {181, 2017, "Dua Lipa", "Bite The Bullet by Dua Lipa (Ft. Trey Campbell)",
     "pop", "party"},
    {182, 2022, "Dua Lipa",
     "Bite The Bullet (Demo 1) by Dua Lipa (Ft. Trey Campbell)", "pop",
     "party"},
    {183, 2023, "Dua Lipa",
     "Bite The Bullet (Demo 2) by Dua Lipa (Ft. Trey Campbell)", "pop",
     "party"},
    {184, 2021, "Dua Lipa",
     "Bite The Bullet (Demo 3) by Dua Lipa (Ft. Trey Campbell)", "pop",
     "party"},
    {185, 2022, "Dua Lipa", "Blame by Dua Lipa", "pop", "party"},
    {186, 2016, "Dua Lipa", "Blow Your Mind (Mwah) by Dua Lipa", "pop",
     "party"},
    {187, 2016, "Dua Lipa", "Blow Your Mind (Mwah) (Acoustic) by Dua Lipa",
     "pop", "party"},
    {188, 2016, "Dua Lipa",
     "Blow Your Mind (Mwah) (Alex Metric Remix) by Dua Lipa", "pop", "party"},
    {189, 2016, "Dua Lipa",
     "Blow Your Mind (Mwah) (Black Saint Remix) by Dua Lipa", "pop", "party"},
    {190, 2016, "Dua Lipa",
     "Blow Your Mind (Mwah) (Capital Session) by Dua Lipa", "pop", "party"},
    {191, 2021, "Dua Lipa", "Blow Your Mind (Mwah) (Demo) by Dua Lipa", "pop",
     "party"},
    {192, 2016, "Dua Lipa",
     "Blow Your Mind (Mwah) (Karma Kid Remix) by Dua Lipa", "pop", "party"},
    {193, 2016, "Dua Lipa",
     "Blow Your Mind (Mwah) (Night Moves Remix) by Dua Lipa", "pop", "party"},
    {194, 2016, "Dua Lipa",
     "Blow Your Mind (Mwah) (NK-OK x Blue Lab Beats Remix) by Dua Lipa", "pop",
     "party"},
    {195, 2022, "Dua Lipa",
     "Blow Your Mind (Mwah) (Radio Disney Version) by Dua Lipa", "pop",
     "party"},
    {196, 2023, "Tove Lo", "Borderline by Tove Lo", "pop", "party"},
    {197, 2023, "Dua Lipa", "Borderline by Dua Lipa", "pop", "party"},
    {198, 2023, "Tove Lo", "Borderline (Stripped in Brazil) by Tove Lo", "pop",
     "party"},
    {199, 2020, "Dua Lipa", "Boys Will Be Boys by Dua Lipa", "pop", "party"},
    {200, 2020, "Dua Lipa",
     "Boys Will Be Boys [Club Future Nostalgia] (Live from Studio 2054) by Dua "
     "Lipa",
     "pop", "party"},
    {201, 2020, "Dua Lipa", "Boys Will Be Boys (Demo) by Dua Lipa", "pop",
     "party"},
    {202, 2022, "Dua Lipa", "Boys Will Be Boys (Disco Demo) by Dua Lipa", "pop",
     "party"},
    {203, 2020, "Dua Lipa",
     "Boys Will Be Boys (Zach Witness Remix) by Dua Lipa", "pop", "party"},
    {204, 2020, "Dua Lipa & The Blessed Madonna",
     "Boys Will be Boys (Zach Witness Remix) [Mixed] by Dua Lipa & The Blessed "
     "Madonna",
     "pop", "party"},
    {205, 2020, "KIDZ BOP Kids", "Break My Heart by KIDZ BOP Kids", "pop",
     "party"},
    {206, 2020, "Pentatonix", "Break My Heart by Pentatonix", "pop", "party"},
    {207, 2020, "Dua Lipa", "Break My Heart by Dua Lipa", "pop", "party"},
    {208, 2020, "Sapphire (UK)", "Break My Heart by Sapphire (UK)", "pop",
     "party"},
    {209, 2020, "Dua Lipa, Jamiroquai & The Blessed Madonna",
     "Break My Heart / Cosmic Girl (Dimitri From Paris Edit) [Mixed] by Dua "
     "Lipa, Jamiroquai & The Blessed Madonna",
     "pop", "party"},
    {210, 2020, "Dua Lipa",
     "Break My Heart (Jax Jones Midnight Snack Remix) by Dua Lipa", "pop",
     "party"},
    {211, 2020, "Dua Lipa", "Break My Heart (Joris Voorn Remix) by Dua Lipa",
     "pop", "sad"},
    {212, 2020, "Dua Lipa",
     "Break My Heart (Live from Studio 2054) by Dua Lipa", "pop", "sad"},
    {213, 2020, "Dua Lipa & The Blessed Madonna",
     "Break My Heart (Moodymann Remix) [Mixed] by Dua Lipa & The Blessed "
     "Madonna",
     "pop", "sad"},
    {214, 2020, "Dua Lipa", "Break My Heart (Moodyman Remix) by Dua Lipa",
     "pop", "sad"},
    {215, 2020, "Dua Lipa", "Break My Heart (Moon Boots Remix) by Dua Lipa",
     "pop", "sad"},
    {216, 2020, "Dua Lipa", "Break My Heart (Solardo Remix) by Dua Lipa", "pop",
     "sad"},
    {217, 2019,
     "Talhah Yunus, Lil Muslim, Mr Mani, Soul Kid, JJ47, Talha Anjum (Ft. "
     "JJ47, Lil Muslim, Mr Mani, Soul Kid, Talha Anjum & Talhah Yunus)",
     "BHAARI HAIN by Talhah Yunus, Lil Muslim, Mr Mani, Soul Kid, JJ47, Talha "
     "Anjum (Ft. JJ47, Lil Muslim, Mr Mani, Soul Kid, Talha Anjum & Talhah "
     "Yunus)",
     "hip-hop", "party"},
    {218, 2022, "Bruno Mars, Post Malone & Camila Cabello",
     "24K Magic / Wow. / My Oh My / Havana [Mixed] by Bruno Mars, Post Malone "
     "& Camila Cabello (Ft. DaBaby)",
     "pop-rap", "party"},
    {219, 2016, "Post Malone", "40 Funk by Post Malone", "pop-rap", "party"},
    {220, 2018, "Post Malone", "92 Explorer by Post Malone", "pop-rap",
     "party"},
    {221, 2020, "Post Malone",
     "About a Girl by Post Malone (Ft. Brian Lee, Nick Mac & Travis Barker)",
     "pop-rap", "party"},
    {222, 2020, "ScarySoundMakerz",
     "AFTERLIFE by ScarySoundMakerz (Ft. AlexAintDead, Bugs Drugs & Lil Ally "
     "En)",
     "pop-rap", "party"},
    {223, 2020, "Post Malone", "Akdmf by Post Malone", "pop-rap", "party"},
    {224, 2022, "Logan Cole",
     "A Light Shinging Trough The Sky by Logan Cole (Ft. Post Malone)",
     "pop-rap", "party"},
    {225, 2017, "Post Malone", "All Apologies by Post Malone", "pop-rap",
     "party"},
    {226, 2019, "Post Malone", "Allergic by Post Malone", "pop-rap", "party"},
    {227, 2018, "21 Savage", "all my friends by 21 Savage (Ft. Post Malone)",
     "pop-rap", "party"},
    {228, 2021, "Ty Dolla $ign",
     "All My Friends (Demo) by Ty Dolla $ign (Ft. Post Malone)", "pop-rap",
     "party"},
    {229, 2015, "Blake Banks",
     "America by Blake Banks (Ft. Post Malone & SauceLordRich)", "pop-rap",
     "party"},
    {230, 2015, "Post Malone", "Another Cup by Post Malone (Ft. FKi)",
     "pop-rap", "party"},
    {231, 2021, "Roddy Ricch", "Antisocial by Roddy Ricch (Ft. Post Malone)",
     "pop-rap", "party"},
    {232, 2022, "Post Malone",
     "Apart by Post Malone (Ft. DaBaby, Dua Lipa & Roddy Ricch)", "pop-rap",
     "party"},
    {233, 2021, "Genius",
     "Artist Archive: Post Malone by Genius (Ft. Post Malone)", "pop-rap",
     "party"},
    {234, 2019, "Post Malone", "A Thousand Bad Times by Post Malone", "pop-rap",
     "party"},
    {235, 2022, "Jaydarapper$",
     "Baby love by Jaydarapper$ (Ft. Juice & Post Malone)", "pop-rap", "party"},
    {236, 2018, "Post Malone", "Ball For Me by Post Malone (Ft. Nicki Minaj)",
     "pop-rap", "party"},
    {237, 2018, "Post Malone",
     "Ball For Me (Demo) by Post Malone (Ft. Nicki Minaj)", "pop-rap", "party"},
    {238, 2020, "Post Malone", "Belong To Me by Post Malone", "pop-rap",
     "party"},
    {239, 2019, "Theresa Rex", "Better Now by Theresa Rex", "pop-rap", "party"},
    {240, 2018, "Nik Nocturnal",
     "Better Now by Nik Nocturnal (Ft. Elektra Amber)", "pop-rap", "party"},
    {241, 2018, "Yuna", "Better Now by Yuna", "pop-rap", "party"},
    {242, 2018, "Post Malone", "Better Now by Post Malone", "pop-rap", "party"},
    {243, 2020, "KIDZ BOP Fanpage", "Better Now by KIDZ BOP Fanpage", "pop-rap",
     "party"},
    {244, 2018, "Megan Nicole", "Better Now by Megan Nicole", "pop-rap",
     "party"},
    {245, 2018, "Roll for It", "Better Now by Roll for It", "pop-rap", "party"},
    {246, 2018, "KIDZ BOP Kids", "Better Now by KIDZ BOP Kids", "pop-rap",
     "party"},
    {247, 2023, "Bailey Rushlow", "Better Now by Bailey Rushlow", "pop-rap",
     "party"},
    {248, 2018, "Troye Sivan", "Better Now by Troye Sivan", "pop-rap", "party"},
    {249, 2018, "Dean Raven", "Better Now (Acoustic) by Dean Raven", "pop-rap",
     "party"},
    {250, 2022, "Latto, Post Malone, Jack Harlow & J. Cole",
     "Big Energy / I Like You (A Happier Song) / First Class / No Role Modelz "
     "(Mixed) by Latto, Post Malone, Jack Harlow & J. Cole (Ft. Doja Cat)",
     "pop-rap", "party"},
    {251, 2016, "Post Malone", "Big Lie by Post Malone", "pop-rap", "party"},
    {252, 2020, "Post Malone",
     "Big Lie (Demo) by Post Malone (Ft. Ty Dolla $ign)", "pop-rap", "party"},
    {253, 2016, "Post Malone", "Big Lie (Instrumental) by Post Malone",
     "pop-rap", "sad"},
    {254, 2018, "Post Malone", "Blame It On Me by Post Malone", "pop-rap",
     "party"},
    {255, 2020, "Post Malone", "Blow It All* by Post Malone", "pop-rap",
     "party"},
    {256, 2016, "Era Istrefi",
     "Bonbon (Post Malone Remix) by Era Istrefi (Ft. Post Malone)", "pop-rap",
     "party"},
    {257, 2011, "Post Malone", "Borkowski by Post Malone", "pop-rap", "party"},
    {258, 2015, "Post Malone", "Boy Bandz by Post Malone", "pop-rap", "party"},
    {259, 2022, "Beyoncé, Post Malone, The Weeknd & Gesaffelstein",
     "BREAK MY SOUL / Wow. / Lost in the Fire (Mixed) by Beyoncé, Post Malone, "
     "The Weeknd & Gesaffelstein",
     "pop-rap", "sad"},
    {260, 2020, "Post Malone",
     "Breed by Post Malone (Ft. Brian Lee, Nick Mac & Travis Barker)",
     "pop-rap", "party"},
    {261, 2016, "Post Malone", "Broken Whiskey Glass by Post Malone", "pop-rap",
     "sad"},
    {262, 2016, "Post Malone",
     "Broken Whiskey Glass (Instrumental) by Post Malone", "pop-rap", "sad"},
    {263, 2023, "Tyla Yaweh", "Bullshit by Tyla Yaweh (Ft. Post Malone)",
     "pop-rap", "party"},
    {264, 2021, "Post Malone", "Bullshit by Post Malone (Ft. Tyla Yaweh)",
     "pop-rap", "party"},
    {265, 2017, "Rexx Life Raj", "Burn Baby Burn by Rexx Life Raj (Ft. Russ)",
     "pop-rap", "party"},
    {266, 2017, "?watt", "Burning Man by ?watt (Ft. Post Malone)", "pop-rap",
     "party"},
    {267, 2012, "Post Malone", "Burn It Down by Post Malone (Ft. Connor Musch)",
     "pop-rap", "party"},
    {268, 2023, "Post Malone", "Buyer Beware by Post Malone", "pop-rap",
     "party"},
    {269, 2016, "DJ Drama",
     "Cameras by DJ Drama (Ft. FKi 1st, Lil Uzi Vert, Mac Miller & Post "
     "Malone)",
     "pop-rap", "party"},
    {270, 2016, "Flosstradamus, FKi1st & graves",
     "Came Up by Flosstradamus, FKi1st & graves (Ft. KEY! & Post Malone)",
     "pop-rap", "party"},
    {271, 2017, "Flosstradamus, FKi1st & graves",
     "Came Up (Casper & B. Remix) by Flosstradamus, FKi1st & graves (Ft. KEY! "
     "& Post Malone)",
     "pop-rap", "party"},
    {272, 2017, "Flosstradamus, FKi1st & graves",
     "Came Up (graves & Clips X Ahoy VIP Edit) by Flosstradamus, FKi1st & "
     "graves (Ft. Post Malone)",
     "pop-rap", "party"},
    {273, 2017, "Flosstradamus, FKi1st & graves",
     "Came Up (Jorgen Odegard Remix) by Flosstradamus, FKi1st & graves (Ft. "
     "Post Malone)",
     "pop-rap", "party"},
    {274, 2015, "Post Malone",
     "Came Up (Original Version) by Post Malone (Ft. KEY!)", "pop-rap",
     "party"},
    {275, 2017, "Flosstradamus, FKi1st & graves",
     "Came Up (Rickyxsan Remix) by Flosstradamus, FKi1st & graves (Ft. Post "
     "Malone)",
     "pop-rap", "party"},
    {276, 2017, "Post Malone", "Candy Paint by Post Malone", "pop-rap",
     "party"},
    {277, 2019, "DJ Khaled",
     "Celebrate by DJ Khaled (Ft. Post Malone & Travis Scott)", "pop-rap",
     "party"},
    {279, 2023, "Post Malone", "Chemical by Post Malone", "pop-rap", "party"},
    {280, 2022, "Post Malone",
     "Chip 'n Dale Rescue Rangers Theme by Post Malone", "pop-rap", "party"},
    {281, 2023, "Ali Zafar", "Aasman by Ali Zafar", "pop-rock", "party"},
    {282, 2020, "Ali Zafar", "Ajj Din Veh?e Vich by Ali Zafar", "pop-rock",
     "party"},
    {283, 2022, "Ali Zafar", "Akhiyaan by Ali Zafar", "pop-rock", "party"},
    {284, 2021, "Ali Zafar", "Balaghal Ula Bi Kamaalihi by Ali Zafar",
     "pop-rock", "party"},
    {285, 2003, "Ali Zafar", "Chal Dil Merey by Ali Zafar", "pop-rock", "sad"},
    {286, 2003, "Ali Zafar", "Channo by Ali Zafar", "pop-rock", "party"},
    {287, 2018, "Ali Zafar (Ft. Aima Baig)",
     "Chan Ve by Ali Zafar (Ft. Aima Baig)", "pop-rock", "party"},
    {288, 2021, "Ali Zafar", "Dekha by Ali Zafar", "pop-rock", "happy"},
    {289, 2018, "Ali Zafar (Ft. Aima Baig)",
     "Item Number by Ali Zafar (Ft. Aima Baig)", "pop-rock", "party"},
    {290, 2017, "Ali Zafar", "Jaan-E-Bahaaraan by Ali Zafar", "pop-rock",
     "sad"},
    {291, 2011, "Ali Zafar", "Jhoom - R&B Mix by Ali Zafar", "pop-rock",
     "party"},
    {292, 2017, "Ali Zafar (Ft. Danny Zee)",
     "Julie by Ali Zafar (Ft. Danny Zee)", "pop-rock", "party"},
    {293, 2021, "Ali Zafar (Ft. Gul Panra)",
     "Larsha Pekhawar by Ali Zafar (Ft. Gul Panra)", "pop-rock", "party"},
    {294, 2021, "Ali Zafar (Ft. Shweta Pandit)",
     "Madhubala by Ali Zafar (Ft. Shweta Pandit)", "pop-rock", "party"},
    {295, 2021, "Ali Zafar", "Masty by Ali Zafar", "pop-rock", "party"},
    {296, 2016, "6LACK", "Never Know by 6LACK", "pop-rock", "party"},
    {297, 2022, "Ali Zafar", "Pehli Si Muhabbat by Ali Zafar", "pop-rock",
     "romantic"},
    {298, 2023, "Ali Zafar, Danny Zee", "Raat Din by Ali Zafar, Danny Zee",
     "pop-rock", "romantic"},
    {299, 2003, "Ali Zafar", "Rangeen by Ali Zafar", "pop-rock", "romantic"},
    {300, 2015, "Ali Zafar", "Rockstar by Ali Zafar", "pop-rock", "party"},
    {301, 2006, "Ali Zafar", "Sajania by Ali Zafar", "pop-rock", "romantic"},
    {302, 2018, "Ali Zafar (Ft. Aima Baig)",
     "Sajna Door by Ali Zafar (Ft. Aima Baig)", "pop-rock", "romantic"},
    {303, 2020, "Ali Zafar", "Thehree Si Zindagi by Ali Zafar", "pop-rock",
     "sad"},
    {304, 2017, "Ali Zafar (Ft. Ali Hamza & Strings)",
     "Us Rah Par by Ali Zafar (Ft. Ali Hamza & Strings)", "pop-rock", "sad"},
    {305, 2022, "Ali Zafar", "Voh Dekhnay Mein by Ali Zafar", "pop-rock",
     "party"},
    {306, 2010, "Atif Aslam", "Aa Bhi Ja Sanam by Atif Aslam",
     "pop-rock"
     "sad"},
    {307, 2005, "Atif Aslam", "Aadat by Atif Aslam", "pop-rock", "sad"

    },
    {308, 2022, "Atif Aslam", "Aadat (Deep Blue Version) by Atif Aslam",
     "pop-rock", "sad"},
    {309, 2019, "Atif Aslam", "Aaye Kuch Abr by Atif Aslam", "pop-rock",
     "romantic"},
    {310, 2013,
     "Atif Aslam (Ft. Anushka Manchanda, Michie One, Pritam, Ritu Pathak & "
     "Vishal Dadlani)",
     "Allah Duhai Hai by Atif Aslam (Ft. Anushka Manchanda, Michie One, "
     "Pritam, Ritu Pathak & Vishal Dadlani)",
     "pop-rock", "party"},
    {311, 2019, "Atif Aslam", "Anjaana by Atif Aslam", "pop-rock", "sad"},
    {312, 2018, "Genius Romanizations (Ft. Atif Aslam)",
     "Atif Aslam - Dil Meri Na Sune (Romanized) by Genius Romanizations (Ft. "
     "Atif Aslam)",
     "pop-rock", "party"},
    {313, 2005, "Genius Romanizations",
     "Atif Aslam - Woh Lamhe Woh Baatein (Romanized) by Genius Romanizations",
     "pop-rock"
     "sad"},
    {314, 2019, "Atif Aslam", "Auliya by Atif Aslam", "pop-rock", "party"},
    {315, 2019, "Atif Aslam", "Baarishein by Atif Aslam", "pop-rock",
     "romantic"},
    {316, 2019, "Genius Romanizations (Ft. Atif Aslam)",
     "Baarishein (Romanized) by Genius Romanizations (Ft. Atif Aslam)",
     "pop-rock", "romantic"},
    {317, 2021, "Atif Aslam", "Bakhuda Tumhi Ho by Atif Aslam", "pop-rock",
     "romantic"},
    {318, 2012, "Atif Aslam (Ft. Sunidhi Chauhan)",
     "Be Intehaan by Atif Aslam (Ft. Sunidhi Chauhan)", "pop-rock", "romantic"},
    {319, 2022, "Atif Aslam", "Bheegi Yaadein by Atif Aslam", "pop-rock",
     "sad"},
    {320, 2021, "Loka", "BHEEGI YAADEIN by Loka", "pop-rock", "sad"},
    {321, 2021, "Atif Aslam",
     "Chale To Kat Hi Jayega (Urdu Version) by Atif Aslam", "pop-rock", "sad"},
    {322, 2012, "Atif Aslam (Ft. Qayaas)",
     "Charkha Nolakha by Atif Aslam (Ft. Qayaas)", "pop-rock", "party"},
    {323, 2021, "Talal Qureshi, Atif Aslam & Faris Shafi",
     "Cricket Khidaiye by Talal Qureshi, Atif Aslam & Faris Shafi", "pop-rock",
     "happy"},
    {324, 2017, "Atif Aslam", "Darasal by Atif Aslam", "pop-rock", "romantic"},
    {325, 2018, "Atif Aslam", "Dekhte Dekhte by Atif Aslam", "pop-rock", "sad"},
    {326, 2017, "Atif Aslam", "Dil Diyan Gallan by Atif Aslam", "pop-rock",
     "romantic"},
    {327, 2022, "Atif Aslam", "Dil Meri Na Sune by Atif Aslam", "pop-rock",
     "romantic"},
    {328, 2021, "Atif Aslam (Ft. Payal Dev)",
     "Dil Meri Na Sune (Reprise) by Atif Aslam (Ft. Payal Dev)", "pop-rock",
     "romantic"},
    {329, 2020, "Atif Aslam", "Doorie by Atif Aslam", "pop-rock", "sad"},
    {330, 2021, "Atif Aslam", "Doorie (Energy Mix) by Atif Aslam", "pop-rock",
     "sad"},
    {331, 2021, "Atif Aslam", "Doorie (House Mix) by Atif Aslam", "pop-rock",
     "sad"},
    {332, 2021, "Atif Aslam", "Do pal ka/Dunia humein by Atif Aslam",
     "pop-rock", "sad"},
    {333, 2021, "Atif Aslam (Ft. Payal Dev)",
     "Dil Meri Na Sune (Reprise) by Atif Aslam (Ft. Payal Dev)", "pop-rock",
     "romantic"},
    {334, 2022, "Atif Aslam", "Doorie by Atif Aslam", "pop-rock", "sad"},
    {335, 2020, "Atif Aslam", "Doorie (Energy Mix) by Atif Aslam", "pop-rock",
     "sad"},
    {336, 2022, "Atif Aslam", "Doorie (House Mix) by Atif Aslam", "pop-rock",
     "sad"},
    {337, 2021, "Atif Aslam", "Do pal ka/Dunia humein by Atif Aslam",
     "pop-rock", "romantic"},
    {338, 2022, "Atif Aslam", "Ehsaas by Atif Aslam", "pop-rock", "sad"},
    {339, 2022, "Atif Aslam", "Ehsaas (Freaky Mix) by Atif Aslam", "pop-rock",
     "sad"},
    {340, 2021, "Atif Aslam", "Gal Sun Ja by Atif Aslam", "pop-rock", "party"},
    {341, 2022, "Abdullah Siddiqui (Ft. Atif Aslam)",
     "Go by Abdullah Siddiqui (Ft. Atif Aslam)", "pop-rock", "party"},
    {342, 2020, "Atif Aslam", "Hum Kis Galli Ja Rahe by Atif Aslam", "pop-rock",
     "romantic"},
    {343, 2021, "Atif Aslam", "Humrahi by Atif Aslam", "pop-rock", "sad"},
    {344, 2016, "Maher Zain - ???? ??? (Ft. Atif Aslam)",
     "I'm Alive by Maher Zain - ???? ??? (Ft. Atif Aslam)", "pop-rock", "sad"},
    {345, 2019, "Atif Aslam", "In Dinon by Atif Aslam", "pop-rock", "sad"},
    {346, 2021, "Atif Aslam", "Jab koi baat by Atif Aslam", "pop-rock",
     "happy"},
    {347, 2022, "Atif Aslam", "Jal Pari by Atif Aslam", "pop-rock", "sad"},
    {348, 2013, "Atif Aslam", "Janam Janam by Atif Aslam",
     "pop-rock"
     "romantic"},
    {349, 2013, "Pritam (Ft. Atif Aslam)",
     "Janam Janam (Sad Version) by Pritam (Ft. Atif Aslam)",
     "pop-rock"
     "romantic"},
    {350, 2015, "Atif Aslam", "Jeena Jeena by Atif Aslam",
     "pop-rock"
     "romantic"},
    {351, 2013, "Atif Aslam (Ft. Shreya Ghoshal)",
     "Jeene Laga Hoon by Atif Aslam (Ft. Shreya Ghoshal)", "pop-rock",
     "romantic"},
    {352, 2021, "Atif Aslam", "Joug by Atif Aslam", "pop-rock", "sad"},
    {353, 2020, "Atif Aslam", "Kadi Te Hans by Atif Aslam", "pop-rock",
     "party"},
    {354, 2010, "Atif Aslam", "Kaun Hoon Main by Atif Aslam", "pop-rock",
     "sad"},
    {355, 2023, "Atif Aslam", "Kaun Tha - Kapkapi by Atif Aslam", "pop-rock",
     "sad"},
    {356, 2021, "Atif Aslam", "Khair Mangda by Atif Aslam", "pop-rock",
     "party"},
    {357, 2021, "Atif Aslam", "Kinara by Atif Aslam", "pop-rock", "sad"},
    {358, 2021, "Atif Aslam", "Kuch Is Tarah by Atif Aslam", "pop-rock",
     "romantic"},
    {359, 2022, "Atif Aslam", "Kyun Chor Gaye Rastay by Atif Aslam", "pop-rock",
     "sad"},
    {360, 2023, "Atif Aslam", "Le Jaa Tu Mujhe by Atif Aslam", "pop-rock",
     "romantic"},
    {361, 2020, "Atif Aslam", "Le Ja Tu Mujhe by Atif Aslam", "pop-rock",
     "romantic"},
    {362, 2022, "Atif Aslam", "Mahi Ve by Atif Aslam", "pop-rock", "party"},
    {363, 2020, "Atif Aslam", "Mahi Ve (Eternal Mix) by Atif Aslam", "pop-rock",
     "party"},
    {364, 2020, "Atif Aslam", "Mahiya Ve Soniya by Atif Aslam", "pop-rock",
     "party"},
    {365, 2022, "Atif Aslam", "Mahiya Ve Soniya (Soul Mix) by Atif Aslam",
     "pop-rock", "party"},
    {366, 2013, "Pritam (Ft. Atif Aslam & Chinmayi Sripada)",
     "Main Rang Sharbaton Ka by Pritam (Ft. Atif Aslam & Chinmayi Sripada)",
     "pop-rock", "romantic"},
    {367, 2015, "Googoosh (Ft. Atif Aslam & Gul Panra)",
     "Man Amadeh-Am by Googoosh (Ft. Atif Aslam & Gul Panra)", "pop-rock",
     "happy"},
    {368, 2021, "Atif Aslam", "Maula by Atif Aslam", "pop-rock", "happy"},
    {369, 2021, "Atif Aslam", "Meri Kahani by Atif Aslam", "pop-rock", "sad"},
    {370, 2017, "Arindam Chatterjee (Ft. Atif Aslam & Nikhita Gandhi)",
     "Mithe Alo by Arindam Chatterjee (Ft. Atif Aslam & Nikhita Gandhi)",
     "pop-rock", "happy"},
    {371, 2019, "Banur's Band (Ft. Atif Aslam)",
     "Mubarik Mubarik by Banur's Band (Ft. Atif Aslam)", "pop-rock", "party"},
    {372, 2023, "Atif Aslam", "Old Songs Mashup by Atif Aslam", "pop-rock",
     "party"},
    {373, 2010, "Atif Aslam (Ft. Garima Jhingon)",
     "O Mere Khuda by Atif Aslam (Ft. Garima Jhingon)", "pop-rock", "happy"},
    {374, 2020, "Atif Aslam", "O Mere Khuda (Dance Mix) by Atif Aslam",
     "pop-rock", "happy"},
    {375, 2022, "Joi Barua (Ft. Atif Aslam & Jyotica Tangri)",
     "O'meri Laila by Joi Barua (Ft. Atif Aslam & Jyotica Tangri)", "pop-rock",
     "party"},
    {376, 2022, "Tamal Hadiul (Ft. Atif Aslam, Piran Khan & Sahil Sanjan)",
     "Onubhuti X Tera Hone Laga Hoon by Tamal Hadiul (Ft. Atif Aslam, Piran "
     "Khan & Sahil Sanjan)",
     "pop-rock", "romantic"},
    {377, 2023, "Atif Aslam", "O Re Piya by Atif Aslam", "pop-rock",
     "romantic"},
    {378, 2018, "Atif Aslam (Ft. Atif Aslam)",
     "O SAATHI by Atif Aslam (Ft. Atif Aslam)", "pop-rock", "sad"},
    {379, 2018, "Atif Aslam (Ft. Disha Patani & Tiger Shroff)",
     "O Saathi Lyrics by Atif Aslam (Ft. Disha Patani & Tiger Shroff)",
     "pop-rock", "sad"},
    {380, 2018, "Atif Aslam (Ft. Tulsi Kumar)",
     "Paniyon Sa by Atif Aslam (Ft. Tulsi Kumar)", "pop-rock", "romantic"},
    {381, 2018, "Uliya",
     "Pa Respirar / Woh Lamhe Woh Baatein (Cover) by Uliya", "pop-rock",
     "happy"},
    {382, 2022, "Atif Aslam", "Pehli dafa by Atif Aslam", "pop-rock",
     "romantic"},
    {383, 2008, "Atif Aslam", "Pehli Nazar Mein by Atif Aslam", "pop-rock",
     "romantic"},
    {384, 2012, "Atif Aslam", "Rabba Sacheya by Atif Aslam", "pop-rock",
     "party"},
    {385, 2021, "Atif Aslam (Ft. Atif Aslam)",
     "Rains by Atif Aslam (Ft. Atif Aslam)", "pop-rock", "happy"},
    {386, 2022, "Atif Aslam (Ft. Momina Mustehsan)",
     "Sajan Das Na by Atif Aslam (Ft. Momina Mustehsan)", "pop-rock", "party"},
    {387, 2018, "Atif Aslam", "Sehmi Hai Dhadkan by Atif Aslam", "pop-rock",
     "sad"},
    {388, 2018, "Atif Aslam (Ft. Lulia Vantur)",
     "Selfish by Atif Aslam (Ft. Lulia Vantur)", "pop-rock", "party"},
    {389, 2019, "Peter Gabriel (Ft. Atif Aslam)",
     "Speak (Bol) by Peter Gabriel (Ft. Atif Aslam)", "pop-rock", "party"},
    {390, 2022, "Atif Aslam", "Tajdaar e haram by Atif Aslam", "pop-rock",
     "happy"},
    {391, 2015, "Atif Aslam", "Tajdar-E-Haram by Atif Aslam", "pop-rock",
     "happy"},
    {
        392,
        2021,
        "Atif Aslam",
        "Tehzeeb by Atif Aslam",
        "pop-rock",
        "party",
    },
    {393, 2009, "Atif Aslam (Ft. Alisha Chinai)",
     "Tera Hone Laga Hoon by Atif Aslam (Ft. Alisha Chinai)", "pop-rock",
     "romantic"},
    {394, 2018, "Atif Aslam", "Tera Hua by Atif Aslam", "pop-rock", "sad"},
    {395, 2018, "Genius Romanizations (Ft. Atif Aslam)",
     "Tera Hua (Romanized) by Genius Romanizations (Ft. Atif Aslam)",
     "pop-rock", "sad"},
    {396, 2022, "Atif Aslam", "Tera Hua (Unplugged) by Atif Aslam", "pop-rock",
     "sad"},
    {397, 2006, "Atif Aslam", "Tere Bin by Atif Aslam", "pop-rock", "sad"},
    {398, 2010, "Atif Aslam (Ft. Shreya Ghoshal)",
     "Tere Liye by Atif Aslam (Ft. Shreya Ghoshal)", "pop-rock", "sad"},
    {399, 2018, "Mannan Shaah (Ft. Akanksha Bhandari & Atif Aslam)",
     "Tere Liye by Mannan Shaah (Ft. Akanksha Bhandari & Atif Aslam)",
     "pop-rock", "sad"},
    {400, 2017, "Atif Aslam", "Tere Sang Yaara by Atif Aslam", "pop-rock",
     "romantic"},
    {401, 2022, "Pritam (Ft. Atif Aslam)",
     "Tu Chahiye by Pritam (Ft. Atif Aslam)", "pop-rock", "happy"},
    {402, 2009, "Atif Aslam", "Tu Jaane Na by Atif Aslam", "pop-rock",
     "romantic"},
    {403, 2022, "Atif Aslam",
     "Tu Jaane Na Lyrics By Atif Aslam | English Version | by Atif Aslam",
     "pop-rock", "romantic"},
    {404, 2023, "Atif Aslam", "Wohi Khuda by Atif Aslam", "pop-rock", "happy"},
    {405, 2023, "Seedhe Maut (Ft. Faris Shafi)",
     "Asal G by Seedhe Maut (Ft. Faris Shafi)", "hip-hop", "party"},
    {406, 2012, "Faris Shafi (Ft. Mooroo)", "Awaam by Faris Shafi (Ft. Mooroo)",
     "hip-hop", "party"},
    {407, 2018, "Talal Qureshi (Ft. Faris Shafi)",
     "Clap by Talal Qureshi (Ft. Faris Shafi)", "hip-hop", "party"},
    {408, 2021, "Talal Qureshi, Atif Aslam & Faris Shafi",
     "Cricket Khidaiye by Talal Qureshi, Atif Aslam & Faris Shafi", "hip-hop",
     "happy"},
    {409, 2022, "Faris Shafi", "HUM by Faris Shafi", "hip-hop", "party"},
    {410, 2021, "Faris Shafi", "Introduction by Faris Shafi", "hip-hop",
     "party"},
    {411, 2022, "Raftaar (Ft. Faris Shafi)",
     "JASHAN-E-HIP-HOP by Raftaar (Ft. Faris Shafi)", "hip-hop", "happy"},
    {412, 2015, "Faris Shafi", "Jawab De by Faris Shafi", "hip-hop", "party"},
    {413, 2021, "Faris Shafi", "LAFZ by Faris Shafi", "hip-hop", "party"},
    {414, 2021, "Faris Shafi", "Molotov by Faris Shafi", "hip-hop", "party"},
    {415, 2022, "Faris Shafi (Ft. Meesha Shafi)",
     "Muaziz Saarif by Faris Shafi (Ft. Meesha Shafi)", "hip-hop", "party"},
    {416, 2014, "Faris Shafi", "Muskura by Faris Shafi", "hip-hop", "party"},
    {417, 2020, "Faris Shafi", "NAZAR by Faris Shafi", "hip-hop", "party"},
    {418, 2019, "Abdullah Siddiqui (Ft. Faris Shafi)",
     "Prosaic by Abdullah Siddiqui (Ft. Faris Shafi)", "hip-hop", "party"},
    {419, 2022, "Faris Shafi (Ft. Talal Qureshi)",
     "Vitamin D by Faris Shafi (Ft. Talal Qureshi)", "hip-hop", "party"},
    {420, 2018, "Faris Shafi x Ali Sethi", "Waasta by Faris Shafi x Ali Sethi",
     "hip-hop", "party"},
    {421, 2023, "Faris Shafi", "With love by Faris Shafi", "hip-hop", "party"},
    {422, 2022, "Karakoram, Faris Shafi & Talha Anjum",
     "Ye Dunya by Karakoram, Faris Shafi & Talha Anjum", "hip-hop", "party"},
    {423, 2023, "Astrid S (Ft. Asim Azhar)",
     "Darkest Hour (Asim Azhar Version) by Astrid S (Ft. Asim Azhar)", "pop",
     "party"},
    {424, 2018, "Asim Azhar",
     "Dunya cornetto Pop Rock Season 3 lyrics by Asim Azhar by Asim Azhar",
     "pop", "party"},
    {425, 2019, "Asim Azhar & Zenab Fatimah Sultan",
     "Ghalat Fehmi (From \"Superstar\") by Asim Azhar & Zenab Fatimah Sultan",
     "pop", "sad"},
    {426, 2017, "Asim Azhar", "Haasil | ???? by Asim Azhar", "pop", "sad"},
    {427, 2022, "Asim Azhar", "Habibi by Asim Azhar", "pop", "party"},
    {428, 2020, "Asim Azhar", "Habibi - Romanized Urdu by Asim Azhar", "pop",
     "party"},
    {429, 2013, "Asim Azhar", "Hands In The Air by Asim Azhar", "pop", "happy"},
    {430, 2020, "Asim Azhar (Ft. Hania Amir)",
     "Ishqiya OST by Asim Azhar (Ft. Hania Amir)", "pop", "sad"},
    {431, 2018, "Asim Azhar (Ft. Iqra Aziz & Waleed Khalid)",
     "Jo Tu Na Mila by Asim Azhar (Ft. Iqra Aziz & Waleed Khalid)", "pop",
     "sad"},
    {432, 2019, "Asim Azhar", "Jo Tu Na Mila - Acoustic Version by Asim Azhar",
     "pop", "sad"},
    {433, 2020, "Asim Azhar", "Khelta Ja by Asim Azhar", "pop", "sad"},
    {434, 2022, "Asim Azhar", "Maahi Aaja by Asim Azhar",
     "pop"
     "sad"},
    {435, 2020, "Krewella (Ft. Asim Azhar)",
     "Paradise by Krewella (Ft. Asim Azhar)", "pop", "party"},
    {436, 2022, "Asim Azhar (Ft. Asim Azhar)",
     "Pul Ja by Asim Azhar (Ft. Asim Azhar)", "pop", "party"},
    {437, 2020, "Asim Azhar (Ft. Hania Amir)",
     "Sassi by Asim Azhar (Ft. Hania Amir)", "pop", "party"},
    {438, 2020, "Asim Azhar", "Soneya | ????? by Asim Azhar", "pop", "sad"},
    {439, 2014, "Asim Azhar", "Soniye by Asim Azhar", "pop", "sad"},
    {440, 2014, "Asim Azhar", "Sunlay by Asim Azhar", "pop", "party"},
    {441, 2016, "Momina Mustehsan (Ft. Asim Azhar)",
     "Tera Woh Pyar (Nawazishein Karam) by Momina Mustehsan (Ft. Asim Azhar)",
     "pop", "sad"},
    {442, 2020, "Asim Azhar (Ft. Raamis, Shamoon Ismail & Young Stunners)",
     "Tum Tum by Asim Azhar (Ft. Raamis, Shamoon Ismail & Young Stunners)",
     "pop", "party"},
    {443, 2021, "Asim Azhar (Ft. Talha Anjum & Talhah Yunus)",
     "Yaad by Asim Azhar (Ft. Talha Anjum & Talhah Yunus)", "pop", "sad"},
    {444, 2020, "Sonu Nigam", "Aag hun mai by Sonu Nigam", "filmi", "party"},
    {445, 2006, "Alisha Chinai, Mahalakshmi Iyer & Sonu Nigam",
     "Aaj Ki Raat by Alisha Chinai, Mahalakshmi Iyer & Sonu Nigam", "filmi",
     "party"},
    {446, 2020, "Sonu Nigam", "Aakhri Kadam Tak by Sonu Nigam", "filmi",
     "party"},
    {447, 2009, "Sonu Nigam, Swanand Kirkire, Shaan",
     "Aal Izz Well by Sonu Nigam, Swanand Kirkire, Shaan", "filmi", "happy"},
    {448, 2011, "Sonu Nigam", "Abhi Mujh Mein Kahin by Sonu Nigam", "filmi",
     "romantic"},
    {449, 2018, "Santhosh Narayanan (Ft. Chinna, Shweta Mohan & Sonu Nigam)",
     "Agala Eshto Akasha by Santhosh Narayanan (Ft. Chinna, Shweta Mohan & "
     "Sonu Nigam)",
     "filmi", "party"},
    {450, 2006, "Sonu Nigam", "Anisuthide Yaako Indu by Sonu Nigam", "filmi",
     "party"},
    {451, 2020, "Sonu Nigam", "Anisutide yaki indu by Sonu Nigam", "filmi",
     "party"},
    {452, 2018, "Sonu Nigam", "Badan Pe Sitare by Sonu Nigam", "filmi",
     "party"},
    {453, 2021, "Sonu Nigam (Ft. Pranab Biswas & Shreya Ghoshal)",
     "Bande Mein Tha Dum  Vande Mataram by Sonu Nigam (Ft. Pranab Biswas & "
     "Shreya Ghoshal)",
     "filmi", "party"},
    {454, 2023, "Sonu Nigam", "Bandeya by Sonu Nigam", "filmi", "happy"},
    {455, 2018, "Suddho Roy (Ft. Sonu Nigam)",
     "Bhul Ja Korechi Aami by Suddho Roy (Ft. Sonu Nigam)", "filmi", "party"},
    {456, 2001,
     "Sonu Nigam (Ft. Alka Yagnik, Amit Kumar, Kavita Krishnamurthy & Udit "
     "Narayan)",
     "Bole Chudiyan by Sonu Nigam (Ft. Alka Yagnik, Amit Kumar, Kavita "
     "Krishnamurthy & Udit Narayan)",
     "filmi", "happy"},
    {457, 1998, "Sonu Nigam (Ft. Alka Yagnik)",
     "Chal Pyar Karegi by Sonu Nigam (Ft. Alka Yagnik)", "filmi", "party"},
    {458, 2009, "Kylie Minogue (Ft. Sonu Nigam)",
     "Chiggy Wiggy by Kylie Minogue (Ft. Sonu Nigam)", "filmi", "party"},
    {459, 2008, "Sonu Nigam (Ft. A.R. Rahman & Roop Kumar Rathod)",
     "Dil Ka Rishta by Sonu Nigam (Ft. A.R. Rahman & Roop Kumar Rathod)",
     "filmi", "romantic"},
    {460, 2020, "Sonu Nigam (Ft. Alka Yagnik)",
     "Dil Ne Yeh Kaha Hain Dil Se by Sonu Nigam (Ft. Alka Yagnik)", "filmi",
     "romantic"},
    {461, 2020, "Sonu Nigam", "Do Ka Chaar by Sonu Nigam", "filmi", "party"},
    {462, 2022, "Lata Mangeshkar (Ft. Sonu Nigam)",
     "Do Pal by Lata Mangeshkar (Ft. Sonu Nigam)", "filmi", "romantic"},
    {463, 2019, "Natalia Lesz (Ft. Sonu Nigam)",
     "Fire In The Sky by Natalia Lesz (Ft. Sonu Nigam)", "filmi", "party"},
    {464, 2017, "Sonu Nigam (Ft. Palak Muchhal)",
     "Gori Tu Latth Maar by Sonu Nigam (Ft. Palak Muchhal)", "filmi", "party"},
    {465, 2017, "Sonu Nigam", "Gulabi Retro Mix by Sonu Nigam", "filmi",
     "party"},
    {466, 2020,
     "An Initiative by Indian Artists - Project Hope (Ft. Amitabh Bachchan)",
     "Guzar Jayega by An Initiative by Indian Artists - Project Hope (Ft. "
     "Amitabh Bachchan)",
     "filmi", "party"},
    {467, 2017, "Shreya Ghoshal (Ft. Ram Sampath & Sonu Nigam)",
     "Halka Halka by Shreya Ghoshal (Ft. Ram Sampath & Sonu Nigam)", "filmi",
     "party"},
    {468, 2017, "Sonu Nigam (Ft. Shreya Ghoshal)",
     "Hans Mat Pagli by Sonu Nigam (Ft. Shreya Ghoshal)", "filmi", "party"},
    {469, 2022, "Sonu Nigam", "Happy birthday by Sonu Nigam", "filmi", "party"},
    {470, 2022, "Sonu Nigam", "Heer by Sonu Nigam", "filmi", "romantic "},
    {471, 2021, "Jordan Muzik (Ft. Jordan Muzik & Sonu Nigam)",
     "HERO: A TRIBUTE TO SONU SOOD by Jordan Muzik (Ft. Jordan Muzik & Sonu "
     "Nigam)",
     "filmi", "party"},
    {472, 2023, "Sonu Nigam (Ft. Sadhana Sargam)",
     "Hum Ko Maaloom Hain by Sonu Nigam (Ft. Sadhana Sargam)", "filmi",
     "romantic"},
    {473, 2019, "Sonu Nigam", "Ilaahi by Sonu Nigam", "filmi", "party"},
    {474, 1999, "Anuradha Sriram (Ft. A.R. Rahman, Sonu Nigam & Sujatha)",
     "Ishq Bina by Anuradha Sriram (Ft. A.R. Rahman, Sonu Nigam & Sujatha)",
     "filmi", "party"},
    {475, 2009, "Sonu Nigam", "Jaane Nahin Denge Tujhe by Sonu Nigam", "filmi",
     "sad"},
    {476, 2006, "Shankar-Ehsaan-Loy (Ft. Alka Yagnik & Sonu Nigam)",
     "Kabhi Alvida Naa Kehna by Shankar-Ehsaan-Loy (Ft. Alka Yagnik & Sonu "
     "Nigam)",
     "filmi", "sad"},
    {477, 2021, "Jatin-Lalit (Ft. Sonu Nigam)",
     "Kabhi Kushi Kabhie Gham, Pt. 1 (Sad Version 1) by Jatin-Lalit (Ft. Sonu "
     "Nigam)",
     "filmi", "party"},
    {478, 2003, "Shankar-Ehsaan-Loy (Ft. Sonu Nigam)",
     "Kal Ho Naa Ho by Shankar-Ehsaan-Loy (Ft. Sonu Nigam)", "filmi", "sad"},
    {479, 2020, "Sonu Nigam",
     "Kal Ho Naa Ho song Lyrics | Sonu Nigam | Shah Rukh Khan | by Sonu Nigam",
     "filmi", "sad"},
    {480, 2023, "Sonu Nigam", "Kal Ho no ho - Maahi ve by Sonu Nigam", "filmi",
     "sad"},
    {481, 2004,
     "Shankar Mahadevan (Ft. Hariharan, Kunal Ganjawala, Roop Kumar Rathod, "
     "Sonu Nigam & Vijay Prakash)",
     "Kandhon Se Milte Hain Kandhe by Shankar Mahadevan (Ft. Hariharan, Kunal "
     "Ganjawala, Roop Kumar Rathod, Sonu Nigam & Vijay Prakash)",
     "filmi", "sad"},
    {482, 2006, "Sonu Nigam (Ft. Shreya Ghoshal)",
     "Koi Tumsa Nahin by Sonu Nigam (Ft. Shreya Ghoshal)", "filmi", "romantic"},
    {483, 2023, "Lata Mangeshkar (Ft. Sonu Nigam & Yash Chopra)",
     "Kyon Hawa by Lata Mangeshkar (Ft. Sonu Nigam & Yash Chopra)", "filmi",
     "party"},
    {484, 2020, "Sonu Nigam (Ft. Jaspinder Narula)",
     "Life Ban Jaayegi by Sonu Nigam (Ft. Jaspinder Narula)", "filmi", "party"},
    {485, 2003,
     "Shankar-Ehsaan-Loy (Ft. Madhushree, Sadhana Sargam, Shankar Mahadevan, "
     "Sonu Nigam & Udit Narayan)",
     "Maahi Ve by Shankar-Ehsaan-Loy (Ft. Madhushree, Sadhana Sargam, Shankar "
     "Mahadevan, Sonu Nigam & Udit Narayan)",
     "filmi", "party"},
    {486, 2007, "Sonu Nigam (Ft. Shreya Ghoshal)",
     "Main Agar Kahoon by Sonu Nigam (Ft. Shreya Ghoshal)", "filmi",
     "romantic"},
    {487, 2018, "Sonu Nigam & Sunidhi Chauhan",
     "Main Badhiya Tu Bhi Badhiya by Sonu Nigam & Sunidhi Chauhan", "filmi",
     "party"},
    {488, 2004, "Sonu Nigam (Ft. Shreya Ghoshal)",
     "Main Hoon Na by Sonu Nigam (Ft. Shreya Ghoshal)", "filmi", "happy"},
    {489, 2007, "Sonu Nigam (Ft. Javed Ali)",
     "Nagada Nagada by Sonu Nigam (Ft. Javed Ali)", "filmi", "party"},
    {490, 2022, "Sonu Nigam", "Na Jaane Mera Kya Hoga by Sonu Nigam", "filmi",
     "happy"},
    {491, 2007, "Sonu Nigam", "Ninnindale by Sonu Nigam", "filmi", "party"},
    {492, 2020, "Asha Bhosle (Ft. Mohammed Rafi & Sonu Nigam)",
     "O haseena zulfonwale jane jahan by Asha Bhosle (Ft. Mohammed Rafi & Sonu "
     "Nigam)",
     "filmi", "party"},
    {493, 2020, "Shreya Ghoshal (Ft. Sonu Nigam)",
     "Oh My Love by Shreya Ghoshal (Ft. Sonu Nigam)", "filmi", "party"},
    {494, 2006, "Sonu Nigam (Ft. Shreya Ghoshal)",
     "Pal Pal  Har Pal by Sonu Nigam (Ft. Shreya Ghoshal)", "filmi",
     "romantic"},
    {495, 2008, "Sonu Nigam", "Phir Milenge Chalte Chalte by Sonu Nigam",
     "filmi", "party"},
    {496, 2006, "Sonu Nigam (Ft. Shreya Ghoshal)",
     "Pyaar Ki Ek Kahani by Sonu Nigam (Ft. Shreya Ghoshal)", "filmi",
     "romantic"},
    {497, 2021, "Sonu Nigam", "Saathiya by Sonu Nigam", "filmi", "party"},
    {498, 2006,
     "Sonu Nigam (Ft. Kunal Ganjawala, Sadhana Sargam, Shankar Mahadevan & "
     "Shreya Ghoshal)",
     "Salaam-E-Ishq by Sonu Nigam (Ft. Kunal Ganjawala, Sadhana Sargam, "
     "Shankar Mahadevan & Shreya Ghoshal)",
     "filmi", "party"},
    {499, 2020, "R.J. Khan", "Sandese Aaate Hain by R.J. Khan", "filmi",
     "party"},
    {500, 1999, "Sonu Nigam (Ft. Roop Kumar Rathod)",
     "Sandese Aate Hai by Sonu Nigam (Ft. Roop Kumar Rathod)", "filmi",
     "party"},
    {501, 2015, "Sonu Nigam (Ft. Neeti Mohan)",
     "Sapna Jahan by Sonu Nigam (Ft. Neeti Mohan)", "filmi", "party"},
    {502, 2021, "Sonu Nigam (Ft. Kavita Krishnamurthy)",
     "Satrangi Re by Sonu Nigam (Ft. Kavita Krishnamurthy)", "filmi", "party"},
    {503, 2019, "Sonu Nigam", "Shart by Sonu Nigam", "filmi", "party"},
    {504, 2013, "Sonu Nigam (Ft. Teesha Nigam)",
     "Singh Saab The Great by Sonu Nigam (Ft. Teesha Nigam)", "filmi", "party"},
    {505, 2020,
     "Salim-Sulaiman (Ft. Kunal Ganjawala, Richa Sharma, Sonu Nigam & Sunidhi "
     "Chauhan)",
     "Tauba Tauba by Salim-Sulaiman (Ft. Kunal Ganjawala, Richa Sharma, Sonu "
     "Nigam & Sunidhi Chauhan)",
     "filmi", "party"},
    {506, 1998, "Jaspinder Narula (Ft. Sonu Nigam)",
     "Tera Rang Balle Balle by Jaspinder Narula (Ft. Sonu Nigam)", "filmi",
     "party"},
    {507, 2022, "Sonu Nigam (Ft. Meet Bros)",
     "TOTTA by Sonu Nigam (Ft. Meet Bros)", "filmi", "party"},
    {508, 2022, "Sonu Nigam", "Tu by Sonu Nigam", "filmi", "party"},
    {509, 2023, "Sonu Nigam (Ft. Shreya Ghoshal)",
     "Tu Hai Sheetal Dhaara by Sonu Nigam (Ft. Shreya Ghoshal)", "filmi",
     "party"},
    {510, 2004, "Sonu Nigam & Sabri Brothers",
     "Tumse Milke Dil Ka by Sonu Nigam & Sabri Brothers", "filmi", "party"},
    {511, 2017, "KSHMR (Ft. Sonu Nigam)",
     "Underwater by KSHMR (Ft. Sonu Nigam)", "filmi", "party"},
    {512, 2019, "Sonu Nigam (Ft. Ekta Kapoor)",
     "Vande Mataram by Sonu Nigam (Ft. Ekta Kapoor)", "filmi", "party"},
    {513, 2022, "Sonu Nigam", "Yeh ishq hai by Sonu Nigam", "filmi", "party"},
    {514, 2012, "Sonu Nigam (Ft. Shweta Pandit)",
     "Yeh Joker by Sonu Nigam (Ft. Shweta Pandit)", "filmi", "party"},
    {515, 2009, "Sonu Nigam & Shreya Ghoshal",
     "Zoobi Doobi by Sonu Nigam & Shreya Ghoshal", "filmi", "party"},
    {516, 2017, "Weeknd", "Starboy by Weeknd", "pop", "party"},
    {517, 2020, "Weeknd", "After Hours by Weeknd", "pop", "sad"},
    {518, 2019, "Weeknd", "Call Out My Name by Weeknd", "pop", "sad"},
    {519, 2019, "Weeknd", "I Was Never There by Weeknd", "pop", "sad"},
    {520, 2020, "Weeknd", "Try Me by Weeknd", "pop", "sad"},
};
